
const CRACK_COUNT = 20;
const MAX_CRACKS = 1000;
const INITIAL_CRACKS = 5;
const COLOR = undefined;

let CONFIG = {
    CRACK_COUNT: CRACK_COUNT,
    MAX_CRACKS: MAX_CRACKS,
    INITIAL_CRACKS: INITIAL_CRACKS,
    COLOR: COLOR
};

export default CONFIG;